---

- hosts: all
  become: true
  tasks:
  
  - name: Install Prerequisites
    apt:
      update_cache: yes
      name: 
        - ca-certificates
        - curl
        - apt-transport-https
        - software-properties-common
  - name: Add Dcoker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  
  - name: Add Dcoker Repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

  - name: Update Packages
    apt:
      update_cache: true

  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
