--- 

- hosts: all
  become: true
  tasks:
    
    - name: Stop And Disable Gitlab Runner Service
      service: 
        name: gitlab-runner
        state: stopped
        enabled: no
    
    - name: Remove Gitlab Runner
      apt:
        name: gitlab-runner
        state: absent

    - name: Update Packages
      apt:
        update_cache: yes
